const engLiterals = {
  home: {
    slogan: "FIBBO : The art of expressing your art",
    sentence1:
      "Marketplace focused with special emphasis on artists and content creators.",
    title2: "Join our community",
    sentence2:
      "Verify yourself as an Artist and contribute your talent to the ecosystem. Enjoy the advantages of being part of our active community",
    title3: "Help us create your ideal product",
    sentence3:
      "Suggest changes to the Marketplace and get rewarded for your help",
    buttonCreate: "Create",
    buttonExplore: "Explore",
    buttonVerify: "Verify Account",
    buttonSuggestion: "Suggest changes",
  },
  home2: {
    title1: "Exodus: The first JC Cepeda NFT collection",
    text1: "Exodus is a collection made up of 25 tokenized physical works, the physical works will be exhibited in the Senate of the Republic of Mexico in February 2023.",
    title2: "The conquest",
    text2: "It is the first NFT of the collection, the physical work will be shot and its value transferred to the digital asset.",
    title3:"Do you want to create your collection with us?",
  },
  verify: {
    title: "Why verify myself as an Artist?",
    title1: "Create NFTs",
    sentence1:
      "You will be able to mint and put your artistic works up for sale, benefiting from the royalties",
    title2: "Suggest changes",
    sentence2: "You will be able to help scale the marketplace, being rewarded",
    title3: "Reduced fees",
    sentence3:
      "If you are a verified artist, we will assume a large part of the commissions",
  },
  navbar: {
    searchItems: "Search nfts...",
    verify: "Verify!",
    collections: "Collections",
    connectWallet: "Connect Wallet",
    noItem: "No nfts found...",
    noProfile: "No profiles found...",
    noCollections: "No Collections found...",
    profiles: "Profiles",
    nfts: "Nfts",
  },
  userMenu: {
    profile: "Profile",
    settings: "Settings",
    community: "Community",
    station: "FTM Station",
    disconnect: "Disconnect",
    darkMode: "Dark Mode",
    autoDarkMode: "Auto Dark Mode",
    myCollections: "My Collections",
    buyFTM: "Buy FTM",
  },
  filters: {
    filters: "Filters",
    state: "Status",
    onSale: "On Sale",
    offered: "Has Offers",
    onAuction: "On Auction",
    hasBids: "Has Bids",
    clearAll: "Clear All",
    colections: "Collections",
    transfers: "Transfers",
    listings: "Listings",
    offers: "Offers",
    auctions: "Auctions",
    categories: "Categories",
    favorites: "Favorites",
    seeFavorites: "See Favorites",
    contentType: "Content",
    image: "Image",
    video: "Video",
    audio: "Audio",
  },
  explore: {
    filterSort: "Sort By",
    filterRecently: "Recently Created",
    filterOldest: "Oldest",
    filterRecentlyListed: "Recently Listed",
    filterOldestListed: "Oldest Listed",
    filterHighPrice: "Highest Price",
    filterLowPrice: "Lowest Price",
    filterEnding: "Ending Soon",
  },
  detailNFT: {
    price: "Price",
    price2: "Price:",
    offer: "Offer for",
    collection: "Collection",
    chain: "Chain",
    idchain: "Chain ID",
    idtoken: "Token ID",
    royalties: "Royalties",
    recipient: "Recipient",
    filterHistorial: "Filter Activities",
    sales: "Sales",
    transfers: "Transfers",
    listings: "Listings",
    offers: "Offers",
    auctions: "Auctions",
    offerOf: "Offer of",
    expires: "Expires",
    expiresIn: "Expires in",
    actions: "Actions",
    explicitContent: "This article may contain explicit content",
    favorite: "Like NFT",
    unFavorite: "Unlike NFT",
    starts: "Starts in",
    minute: "Minute",
    minutes: "Minutes",
    hour: "Hour",
    hours: "Hours",
    day: "Day",
    days: "Days",
    endsIn: "Ends in",
    offer: "Offer",
    bidBy: "Bid by",
    maximumBid: "Maximum bid",
    minimumBid: "Minimum bid",
    actualPrice: "Actual price",
    buyNowPrice: "Buy now price",
    reservedPrice: "Reserved Price",
    seeAdditional: "See additional content",
    you: "You",
    bidStarts: "Auction starts in {0}  ( {1} )",
    bidEnds: "Auction ends in {0}  ( {1} )",
    highestBid: "Highest Bid",
    putForSale: "List NFT",
    createAuction: "Start Auction",
    update: "Update",
    cancel: "Cancel",
    offeredFor: "Offered for",
  },
  itemPage: {
    chainData: "Chain Data",
    properties: "Properties",
    activity: "Item Activity",
    moreCollection: "More from this collection",
    offers: "Offers",
    owner: "Owner:",
    refreshMeta: "Refresh Metadata",
    fantomNetwork: "Fantom Network",
    itemFreezed: "This NFT is frozen",
    listedFor: "Listed for",
    price: "Price",
    state: "State",
    videoContent: "Video Content",
    audioContent: "Audio Content",
    imageContent: "Image Content",
  },
  itemHistory: {
    event: "Event",
    item: "Item",
    price: "Price",
    initiator: "Initiator",
    recipient: "Recipient",
    date: "Date",
    from: "From",
    to: "To",
  },
  collectionDetail: {
    owners: "Owners",
    notFoundItems: "No NFTs have been found",
    noNFTS: "Collection has no NFTs",
    seeMore: "See More",
    articles: "NFTs",
    totalVolume: "Total Volume",
    creator: "Created By",
  },
  myCollections: {
    mycollections: "My collections",
    text: "Create and manage your exclusives NFT's collections for sharing and selling them",
  },
  collections: {
    search: "Search collections...",
    notFound: "No collections found",
    result: "results",
  },
  createCollection: {
    logo: "Collection logo",
    imgPrincipal: "Collection main image",
    banner: "Collection Banner",
    collectionName: "Collection name",
    collectionName2: "Name:",
    description: "Description",
    description2: "Description:",
    explicit: "Explicit & Sensitive Content",
    logoDesc:
      "Select the logo of the collection that will be visible when browsing the marketplace. The recommended size is 350 x 350.",
    imgPrincipalDesc:
      "Select the main image from the collection. This image will be used to present your collection on the home page or other promotional areas of Fibbo. If no image is selected, the collection logo will be used. The recommended size is 600 x 400.",
    bannerDesc:
      "This image will appear at the top of your collection page. Avoid including too much text in this banner image, as the dimensions change on different devices. The recommended size is 1400 x 350.",
    urlDesc:
      "Customize your URL on Fibbo. Can only contain lowercase letters, numbers, and hyphens.",
    descriptionDesc:
      "The collection description must contain a maximum of 1000 characters.",
    example: "Example: Rock painting",
    descriptionPlaceholder: "Share all the details of your collection",
    selectImage: "Select an image!",
    nameCharacters: "The name must contain between 4 and 30 characters",
    descriptionCharacters:
      "The description must contain between 50 and 1000 characters",

    incorrectFormat: "Not valid format",
    explicitContent: "Explícit or Sensible content",
    imgInput: "Drag or select image files  (MAX 50MB)",
    videoInput: "Drag or select video files (MAX 50MB)",
    imgTypes: "JPG, PNG, JPEG, GIF, SVG, WEBP.",
    videoTypes: "MP4, WMV, AVI, MOV...",
    audioInput: "Drag or select audio files (MAX 50MB)",
    audioTypes: "MP3, MPEG, OGG...",
  },
  profile: {
    collected: "Collected",
    created: "Created",
    activity: "Activity",
    offers: "Offers",
    myOffers: "My offers",
    sentence: "Artist verified by Fibbo team",
    bids: "Bids",
    biddedFor: "Bidded for",
    endsAt: "Ends at",
    favorites: "Favorites",
  },
  profileSettings: {
    settings: "SETTINGS",
    account: "Profile",
    notifications: "Notifications",
    appearance: "Appearance",
    profileSettings: "Profile",
    userName: "User name",
    introduceUserName: "Introduce your username",
    biography: "Biography",
    tellMore: "Tell us more about yourself...",
    email: "Email",
    emailExample: "example@gmail.com",
    wallet: "Wallet",
    profileImg: "Profile image",
    backgroundImg: "Background image",
    selectLenguage: "Select a lenguage:",
    spanish: "Spanish",
    english: "English",
    yourActivityNotifications: "Your Activity Notifications",
    followerActivityNotifications: "Follower Activity Notifications",
    completed: "Your profile has been updated",
  },
  features: {
    suggestions: "Suggestions",
    sentence:
      "Vote and help deciding the evolution of the FIBBO marketplace, the community is the one responsable to add new functionallities to get everyone's product.",
    suggest: "Suggest any change",
    newSuggestion: "New suggestion",
    newSuggestionText:
      "Your suggestion will be reviewed and a value will be assigned by the technical team, once it is accepted and valued it will be shown on the list!",
    newSuggestionTitle: "TITLE",
    newSuggestionDescription: "DESCRIPTION",
    suggestionDoneText:
      "Thank you for your suggestion, we will review your request and process it.",
    proposedFor: "Proposer",
    vote: "Vote",
  },
  makeOffer: {
    offerPrice: "What price do you want to offer?",
    expires: "Expires",
    notWFTM: "You don't have enough FTM",
    offerOf: "Offer of",
  },
  notifications: {
    notifications: "Notifications",
    noNotifications: "You don't have notifications",
    itemOfferted: "Your NFT has been offered",
    offerAccepted: "Your offer has been accepted",
    offerExpired: "Your offer has expired",
    offerModified: "An offer has been modified",
    itemSold: "You have sold your NFT",
    itemBid: "There's a bid on your NFT",
    passedBid: "Your bid have exceeded ",
    auctionWon: "You won the auction",
    bidEnded: "Your bid is ended",
    favListed: "Your favorite NFT has been listed",
    colListed: "A new NFT has been listed",
    favAuction: "Your favorite has been auctioned",
    colAuction: "A new NFT has been auctioned",
    favStarted: "The auction for favorite has started",
    colStarted: "The auction has started",
  },
  actions: {
    makeOffer: "Make Offer",
    close: "Close",
    changePrice: "Change price",
    createCollection: "CREATE COLLECTION",
    addSuggestion: "Make suggestion",
    goToHome: "Go to Homepage",
    verifyAccount: "Verify Account",
    closeWindow: "CLOSE WINDOW",
    saveChanges: "SAVE",
    buyNow: "Buy now",
    buyItem: "Buy NFT",
    makeBid: "Make bid",
    viewYourOffer: "View your offer",
    notEnoughWftm: "Not enough {0} in order to purchase the NFT",
    offerMade: "Succesfuly placed offer of {0} {1}",
    bidPlaced: "",
    goToMyCollections: "Go to my collections",
    processing: "Processing...",
    filter: "Filter",
    noCollections: "There are no collections",
    noCategories: "There are no categories",

    accept: "Accept",
    cancel: "Cancel",
    buy: "Buy",
    createNFT: "Create NFT",
    modifyOffer: "Modify Offer",
    cancelOffer: "Cancel Offer",
    unlist: "Unlist",
    editNFT: "Edit NFT",
    editCollection: "Edit Collection",
    share: "Share",
    moreOptions: "More Options",
    seeInScanner: "See in scanner",
    seeWebsite: "See Website",
    seeDiscord: "See Discord",
    seeTelegram: "See Telegram",
    seeInstagram: "See Instagram",
    deleteNFT: "Remove NFT",
    seeExternalLink: "See External Link",
    sendNFT: "Send NFT",
    addToWatchlist: "Add to watchlist",
    deleteFromWatchlist: "Remove from watchlist",
    addCategory: "Add",
    makeReport: "Make Report",
    reportCollection: "Report Collection",
    reportItem: "Report NFT",
    reportProfile: "Report Account",
    viewNFT: "See NFT",
  },
  modals: {
    connectSentence: "Connect a wallet",
    connectMetamask: "Connect with Metamask",
    artistNotVerified:
      "You are not a verified artist so you can't suggest changes, verify your account and be part of the community!",
    artistNotVerified2:
      "You are not a verified artist to be able to create NFTs on the marketplace, verify your account and be part of the community!",
    URLNotFound:
      "The page you are trying to access does not exist, it is a mystery how you have accessed here. You can press the button to go to the page homepage",
    confirmCreation: "Confirm your creation",
    changedPrice: "NFT listed for {0} {1} correctly",
    offerAccepted: "Succesfully accepted offer for {0} {1}",
    buyNowSuccess: "Succesfully purchased NFT for {0} {1}",
    seeUpdatedItem: "See updated NFT",
    seeOwnedItem: "See NFT in posesion",
    buySuccess: "Succesfully purchased NFT",
    notEnoughWftm: "Not enough {0} to buy the NFT",
    offerMade: "Succesfully placed offer for  {0} {1}",
    bidPlaced: "Succesfully placed  bid for  {0} {1}",
    close: "close",
    sendReport: "Send Report",
    completedReport:
      "Your report has been sent and it will be checked with detail",
    reportDesc: "Report Message",
    reportInfo: "Explain with detail why you are reporting this content",
  },
  acceptOfferModal: {
    acceptOffer: "Accept offer",
    doYouAccept: "Do you want to accept the following offer?",
    isOffering: "Is offering",
  },
  actionModal: {
    error: "An error occurred while performing the action",
  },
  buyItemModal: {
    name: "Name:",
    royalties: "Royalties:",
    notWFTM: "Not enough FTM to buy!",
    fibboEarns: "Fibbo collects 2% commission on each NFT sale",
  },
  buyNowModal: {
    buyItem: "Do you want to buy the NFT for",
  },
  cancelAuctionModal: {
    cancelAuction: "Cancel Auction",
    cancel: "Cancel",
    canceledOk: "Auction successfully canceled",
    reservedPrice: "Reserved Price",
    highestBid: "Highest bid: ",
    doneBy: "Done by:",
    doYouCancel: "Do you want to cancel the auction?",
  },
  changePriceModal: {
    changePrice: "Change NFT price",
    updatedItem: "See updated NFT",
    price: "Price",
  },
  confirmCreateCollection: {
    collectionCreated: "Collection created successfully",
    viewCollection: "See Collection Created",
    customURL: "Custom URL:",
  },
  confirmCreateModal: {
    collection: "Collection:",
    name: "Name:",
    description: "Description",
    royalties: "Royalties",
    aditionalContent: "Additional content",
    createNFT: "Create NFT",
    itemCreated: "NFT created successfully",
    viewItem: "See NFT created",
  },
  createAuctionModal: {
    auctionItem: "Auction NFT",
    auction: "Put up for auction",
    auctionCorrect: "NFT put up for auction successfully",
    choosePrice: "What price do you want to insure?",
    minBid: "Do you want the minimum bid to be the reserved price?",
    buyNowPrice: "Choose buy now price",
    errorPrice: "The buy now price must be at least double the reservation",
    beginDate: "Start date",
    endDate: "End date",
  },
  deleteItemModal: {
    deleteNFT: "Remove NFT",
    delete: "Remove",
    viewCollection: "See collection",
    deletedOk: "The NFT has been successfully deleted",
    ifYouAccept:
      "Once you accept this option, the NFT will be removed from the marketplace and you will not be able to interact with it.",
    confirmDelete: "Are you sure you want to remove it?",
    confirm: "Yes, I'm shure",
  },
  filtersSidebarModal: {
    close: "Close menu",
    token: "Token",
    collections: "Collections",
  },
  freezeMetadataModal: {
    freezeMeta: "Freeze NFT metadata",
    freeze: "Freeze",
    viewItem: "See NFT",
    infoFreezed: "Your NFT information has been successfully frozen",
    ifYouAccept:
      "Once you accept this option, the NFT information cannot be edited and will be stored in a decentralized way in the IPFS protocol",
    correctInfo: "Are you sure the information is correct?",
    yes: "Yes, I'm shure",
  },
  modifyOfferModal: {
    modifyOffer: "Modify offer",
    update: "Update",
    offerUpdated: "Offer updated successfully",
    viewOffer: "See your offer",
    price: "What price do you want to offer?",
    expires: "Expiration date",
  },
  newBidModal: {
    makeBid: "Place bid",
    viewBid: "See your bid",
    reservedPrice: "Reserved price",
    highestBid: "Highest bid:",
    doneBy: "Done by:",
    bidPrice: "What price do you want to bid?",
    biggerBid: "The bid must be higher than the current one",
    text1: "The difference with the current bid must be 1 or bigger",
    text2: "The bid must be bigger than or equal to the reserved price",
  },
  putForSaleModal: {
    sellNft: "Sell NFT",
    sellItem: "Put NFT on Sale",
    viewUpdated: "See updated NFT",
  },
  redirectModal: {
    redirect: "Redirection to external link",
    externalLink: "You will be redirected to an external link",
    fibboNotResponsable: "¡ FIBBO is not responsible for what may happen !",
    dontShow: "Don't show again",
    goToLink: "Go to link",
  },
  removeOfferModal: {
    cancelYourOffer: "Cancel your offer",
    cancelOffer: "Cancel Offer",
    canceledOk: "Offer canceled succesfully",
    updated: "See NFT updated",
    cancel: "Do you want to cancel the offer made?",
    you: "You",
    offer: "offer",
  },
  transferModal: {
    transfer: "Transfer NFT",
    send: "Send NFT",
    sendOk: "NFT sent succesfully",
    itemUpdated: "See iteNFTm updated",
    wallet: "Enter the address to which you want to send it",
  },
  unlistItemModal: {
    quitItem: "Remove NFT from market",
    deleteItem: "Remove ítem",
    deletedOk: "NFT successfully removed from the market",
    itemUpdated: "See NFT updated",
    name: "Name:",
    royalties: "Royalties:",
  },
  updateAuctionModal: {
    updateAuction: "Update Auction",
    update: "Update",
    auctionUpdated: "Auction updated successfully",
    reservedPrice: "Reserved price",
    newPrice: "The new reserved price must be different",
    beginDate: "Start date",
    endDate: "End date",
  },
  wrappedFTMModal: {
    station: "FTM / FTM Station",
    balance: "Balance",
    notFTM: "You don't have enough FTMs to convert",
    notWFTM: "You don't have enough FTM to withdraw",
    changeWFTM: "Convert to FTM",
    sendFTM: "Withdraw FTM",
    close: "Close station",
    succesWrap: "Succesfully wrapped {0} from FTM to FTM",
    succesUnWrap: "Succesfully withdrawed {0} FTM",
  },
  editCollection: {
    title: "Edit Collection",
    notAllowed: "You can't edit the collection, you're not the owner!",
  },
  createItem: {
    colection: "Collection",
    name: "Name",
    description: "Description",
    descriptionDesc: "From 50 to 500 carácteres",
    descriptionError: "The description must have between 50 and 500",
    externalLink: "External Link",
    externalLinkDesc:
      "Fibbo will add a link on the NFT's detail to help the users get more information",
    royalties: "Royalties",
    royaltiesDesc:
      "You'll get a percentatge when a user re-sells the NFT that you've created",
    royaltiesError:
      " The royalties can't be higher than 50% neither a negative value!",
    additionalContent: "Additional Content",
    additionalContentPlaceholder:
      "Add content (Acces key, code, link to files...)",
    additionalContentDesc: "Add Additonal Content that only the owner can see",
    notOwner:
      "You can't create NFTs, You're not the owner of the collection. Create a collection and add NFTs!",
    notOwnerEdit: "You can't edit the NFT, you're not the owner.",
    isFreezed: "The NFT can't be edited, his metadata is freezed",
    notOwnerEdit2:
      "You can't edit the NFT, you're not the owner of the collection",
    freezeMetadata: "Freeze Metadata",
    selectImageError: "Please, select an image file",
    selectVideoError: "Please, select a video file",
    selectAudioError: "Please, select an audio file",
    sizeError: "The media weights more than 50MB, please select another one",
    image: "Image",
    video: "Video",
    audio: "Audio",
  },
  events: {
    minted: "Minted",
    listed: "Listed",
    transfer: "Transfer",
    changedPrice: "Price Updated",
    unlisted: "Unlisted",
    offerCreated: "Offer created",
    offerModified: "Offer modified",
    offerCanceled: "Offer canceled",
    offerAccepted: "Offer accepted",
    auctionCreated: "Auction created",
    bidded: "Bidded",
    auctionUpdate: "Auction Updated",
    auctionCanceled: "Auction canceled",
    auctionEnded: "Auction finished",
  },
};

const espLiterals = {
  home: {
    slogan: "FIBBO : El Arte de expresar tu Arte",
    sentence1:
      "El marketplace para artistas y creadores de contenido. La creatividad nace contigo!",
    title2: "Únete a nuestra comunidad",
    sentence2:
      "Verifícate cómo Artista y aporta tu talento al ecosistema. Disfruta de las ventajas de ser parte de nuestra comunidad activa",
    title3: "Ayúdanos a crear tu producto ideal",
    sentence3:
      "Sugiere cambios a realizar en el Marketplace y recibe recompensas por tu ayuda",
    buttonCreate: "Crear",
    buttonExplore: "Explorar",
    buttonVerify: "Verifícate",
    buttonSuggestion: "Sugerir cambios",
  },
  home2: {
    title1: "Éxodo: La primera colección NFT de JC Cepeda",
    text1: "Éxodo es una colección formada por 25 obras físicas tokenizadas, las obras físicas serán expuestas en el senado de la república de México en Febrero de 2023.",
    title2: "La Conquista",
    text2: "És el primer NFT de la colección, la obra física será tiroteada y su valor trasladado al activo digital.",
    title3:"¿Quieres crear tu colección con nosotros?",
  },
  verify: {
    title: "Porqué verificarme cómo Artista?",
    title1: "Crear NFTs",
    sentence1:
      "Podrás mintear y poner a la venta tus obras artísticas, beneficiandote de los royalties",
    title2: "Sugerir cambios",
    sentence2:
      "Serás capaz de ayudar a escalar el marketplace, siendo recompensado",
    title3: "Fees reducidas",
    sentence3:
      "Si eres un artista verificado, asumiremos gran parte de las comisiones",
  },
  navbar: {
    searchItems: "Buscar NFTs...",
    verify: "Verifícate!",
    collections: "Colecciones",
    connectWallet: "Conectar Billetera",
    noItem: "NFTs no encontrados...",
    noProfile: "Perfiles no encontrados...",
    noCollections: "Colecciones no encontradas...",
    profiles: "Perfiles",
    nfts: "Nfts",
  },
  userMenu: {
    profile: "Perfil",
    settings: "Configuración",
    community: "Comunidad",
    station: "Estación FTM",
    disconnect: "Desconectar",
    darkMode: "Tema Oscuro",
    autoDarkMode: "Auto Tema Oscuro",
    myCollections: "Mis Colecciones",
    buyFTM: "Comprar FTM",
  },
  filters: {
    filters: "Filtros",
    state: "Estado",
    onSale: "En Venta",
    offered: "Ofertado",
    onAuction: "En Subasta",
    hasBids: "Pujado",
    clearAll: "Limpiar Todos",
    colections: "Colecciones",
    transfers: "Transfers",
    listings: "Listados",
    offers: "Ofertas",
    auctions: "Subastas",
    categories: "Categorias",
    favorites: "Favoritos",
    seeFavorites: "Ver Favoritos",
    contentType: "Contenido",
    image: "Imágen",
    video: "Video",
    audio: "Audio",
  },
  explore: {
    filterSort: "Ordenar Por",
    filterRecently: "Creados Recientemente",
    filterOldest: "Mas Antiguos",
    filterRecentlyListed: "Listados Recientemente",
    filterOldestListed: "Listados Mas Antiguos",
    filterHighPrice: "Mas caros",
    filterLowPrice: "Mas Baratos",
    filterEnding: "Termina Antes",
  },
  detailNFT: {
    price: "Precio",
    price2: "Precio:",
    offer: "Ofertado por",
    collection: "Colección",
    chain: "Cadena",
    idchain: "ID Cadena",
    idtoken: "ID Token",
    royalties: "Regalías",
    recipient: "Recipiente",
    filterHistorial: "Filtrar Historial",
    sales: "Ventas",
    transfers: "Transferencias",
    listings: "Listados",
    offers: "Ofertas",
    auctions: "Subastas",
    offerOf: "Oferta de",
    expires: "Expira",
    expiresIn: "Expira en",
    actions: "Acciones",
    explicitContent: "Este NFT tiene contenido explicito",
    favorite: "Favorito",
    unFavorite: "Quitar Favorito",
    starts: "Empieza en",
    minute: "Minuto",
    minutes: "Minutos",
    hour: "Hora",
    hours: "Horas",
    day: "Día",
    days: "Días",
    endsIn: "Acaba en",
    offer: "Oferta",
    bidBy: "Ofertado por",
    maximumBid: "Puja máxima",
    minimumBid: "Puja mínima",
    actualPrice: "Precio Actual",
    buyNowPrice: "Precio Compra ya",
    reservedPrice: "Precio reservado",
    seeAdditional: "Ver contenido adicional",
    you: "Tú",
    bidStarts: "La subasta empieza en {0}  ( {1} )",
    bidEnds: "La subasta termina {0}  ( {1} )",
    highestBid: "Puja mas alta",
    putForSale: "Poner en venta",
    createAuction: "Subastar NFT",
    update: "Actualizar",
    cancel: "Cancelar",
  },
  itemPage: {
    chainData: "Datos de la cadena",
    properties: "Propiedades",
    activity: "Actividad del NFT",
    moreCollection: "Mas de la colección",
    offers: "Ofertas",
    owner: "Pertenece a:",
    refreshMeta: "Refrescar Metadata",
    fantomNetwork: "Red de Fantom",
    itemFreezed: "El NFT tiene sus datos congelados",
    listedFor: "Listado por",
    price: "Precio",
    state: "Estado",
    videoContent: "Contenido de Vídeo",
    audioContent: "Contenido de Audio",
    imageContent: "Contenido de Imágen",
  },
  itemHistory: {
    event: "Evento",
    item: "NFT",
    price: "Precio",
    initiator: "Iniciador",
    recipient: "Recipiente",
    date: "Fecha",
    from: "De",
    to: "A",
  },
  collectionDetail: {
    owners: "Propietarios",
    notFoundItems: "No se han encontrado NFTs",
    noNFTS: "La collección no tiene NFTS",
    seeMore: "Ver más",
    articles: "Articulos",
    totalVolume: "Volumen Total",
    creator: "Creada por",
  },
  myCollections: {
    mycollections: "Mis colecciones",
    text: "Crea y administra tus colecciones de NFTs únicos para poder compartirlos y venderlos.",
  },
  collections: {
    search: "Buscar colecciones...",
    notFound: "No se han encontrado colecciones",
    result: "resultados",
  },
  createCollection: {
    logo: "Logo de la colección",
    imgPrincipal: "Imagen principal de la colección",
    banner: "Pancarta de la colección",
    collectionName: "Nombre de la colección",
    collectionName2: "Nombre:",
    description: "Descripción",
    description2: "Descripción:",
    explicit: "Contenido Explícito o Sensible",
    logoDesc:
      "Selecciona el logo de la colección que será visible al navegar por el marketplace. El tamaño recomendado és 350 x 350.",
    imgPrincipalDesc:
      "Selecciona la imagen de presentación de la colección. Esta imagen se utilizará para presentar su colección en la página de inicio u otras áreas promocionales de Fibbo. Si no se selecciona ninguna imagen, se usará el logo de la colección. El tamaño recomendado és 600 x 400.",
    bannerDesc:
      "Esta imagen aparecerá en la parte superior de la página de tu colección. Evite incluir demasiado texto en esta imagen de banner, ya que las dimensiones cambian en diferentes dispositivos. El tamaño recomendado és 1400 x 350.",
    urlDesc:
      "Personaliza tu URL en Fibbo. Solo puede contener letras minúsculas, números y guiones.",
    descriptionDesc:
      "La descripción de la colección debe contener un máximo de 1000 carácteres.",
    example: "Example: Rock painting",
    descriptionPlaceholder: "Cuenta todo detalle acerca de tu colección!",
    selectImage: "Selecciona una imágen!",
    nameCharacters: "El nombre debe tener entre 4 y 30 carácteres",
    descriptionCharacters:
      "La descripción debe tener entre 50 y 1000 carácteres",
    incorrectFormat: "Formato incorrecto",
    explicitContent: "Contenido Explícito o Sensible",
    imgInput: "Arrastra o selecciona ficheros de imágen (MAX 50MB)",
    videoInput: "Arrastra o selecciona ficheros de video (MAX 50MB)",
    imgTypes: "JPG, PNG, JPEG, GIF, SVG, WEBP.",
    videoTypes: "MP4, WMV, AVI, MOV...",
    audioInput: "Arrastra o selecciona ficheros de audio (MAX 50MB)",
    audioTypes: "MP3, MPEG, OGG...",
  },
  profile: {
    collected: "En posesión",
    created: "Creados",
    activity: "Actividad",
    offers: "Ofertas",
    myOffers: "Mis ofertas",
    sentence: "Artista verificado por el equipo de FIBBO",
    bids: "Pujas",
    biddedFor: "Pujado por",
    endsAt: "Termina en",
    favorites: "Favoritos",
  },
  profileSettings: {
    settings: "CONFIGURACIÓN",
    account: "Perfil",
    notifications: "Notificaciones",
    appearance: "Apariencia",
    profileSettings: "Ajustes de perfil",
    userName: "Nombre de usuario",
    introduceUserName: "Introduce tu nombre de usuario",
    biography: "Biografía",
    tellMore: "Cuentanos más acerca de ti...",
    email: "Correo electrónico",
    emailExample: "ejemplo@gmail.com",
    wallet: "Billetera",
    profileImg: "Imagen de perfil",
    backgroundImg: "Imagen de fondo",
    selectLenguage: "Selecciona un idioma",
    spanish: "Español",
    english: "Inglés",
    yourActivityNotifications: "Tus Notificaciones de Actividad",
    followerActivityNotifications: "Notificaciones de Actividad de Seguidores",
    completed: "Tu perfil ha sido actualizado",
  },
  features: {
    suggestions: "Sugerencias",
    sentence:
      "Vota y contribuye a decidir la evolución del marketplace de FIBBO, la comunidad es la desencadenante de los próximos pasos a añadir para conseguir el producto de todos.",
    suggest: "Sugiere algun cambio",
    newSuggestion: "Nueva sugerencia",
    newSuggestionText:
      "Tu sugerencia será revisada y se le asignará un valor por parte del equipo técnico, una vez sea acceptada y valorada se mostrará en la lista!",
    newSuggestionTitle: "TÍTULO",
    newSuggestionDescription: "DESCRIPCIÓN",
    suggestionDoneText:
      "Gracias por tu sugerencia, revisaremos tu solicitud y la procesaremos.",
    proposedFor: "Proposer",
    vote: "Votar",
  },
  makeOffer: {
    offerPrice: "Que precio quieres ofertar?",
    expires: "Fecha de Expiración",
    notWFTM: "No tienes suficientes FTM",
    offerOf: "Oferta por",
  },
  notifications: {
    notifications: "Notificaciones",
    noNotifications: "No tienes notificaciones",
    itemOfferted: "Tu NFT ha sido ofertado",
    offerAccepted: "Tu oferta ha sido acceptada",
    offerExpired: "Tu oferta ha expirado",
    offerModified: "Han modificado una oferta",
    itemSold: "Has vendido tu NFT",
    itemBid: "Han pujado por tu NFT",
    passedBid: "Han superado tu puja",
    auctionWon: "Has ganado la subasta",
    bidEnded: "Tu puja ha finalizado",
    favListed: "Tu NFT favorito ha sido listado",
    colListed: "Un nuevo NFT ha sido listado",
    favAuction: "Tu favorito ha sido subastado",
    colAuction: "Un nuevo NFT ha sido subastado",
    favStarted: "La subasta de tu favorito ha empezado",
    colStarted: "La subsasta del NFT ha empezado",
  },
  actions: {
    makeOffer: "Realizar Oferta",
    changePrice: "Cambiar precio",
    close: "Cerrar",
    createCollection: "CREAR COLECCIÓN",
    addSuggestion: "Añadir Sugerencia",
    goToHome: "Ir al homepage",
    verifyAccount: "Verificarse",
    closeWindow: "CERRAR VENTANA",
    saveChanges: "GUARDAR CAMBIOS",
    buyNow: "Comprar ya",
    makeBid: "Realizar puja",
    buyItem: "Comprar NFT",
    viewYourOffer: "Ver tu oferta",
    goToMyCollections: "Ir a mis colecciones",
    processing: "Procesando...",
    filter: "Filtrar",
    noCollections: "No se han encontrado colecciones",
    noCategories: "No se han encontrado categorias",

    accept: "Aceptar",
    cancel: "Cancelar",
    buy: "Comprar",
    createNFT: "Crear NFT",
    modifyOffer: "Modificar Oferta",
    cancelOffer: "Cancelar Oferta",
    unlist: "Quitar en venta",
    editNFT: "Editar NFT",
    editCollection: "Editar Colección",
    share: "Compartir",
    moreOptions: "Más opciones",
    seeInScanner: "Ver en scanner",
    seeWebsite: "Ver página web",
    seeDiscord: "Ver discord",
    seeTelegram: "Ver telegram",
    seeInstagram: "Ver Instagram",
    deleteNFT: "Eliminar NFT",
    seeExternalLink: "Ver enlace externo",
    sendNFT: "Enviar NFT",
    addToWatchlist: "Añadir a favoritos",
    deleteFromWatchlist: "Eliminar de favoritos",
    addCategory: "Añadir",
    makeReport: "Realizar Reporte",
    reportCollection: "Reportar Colección",
    reportItem: "Reportar NFT",
    reportProfile: "Reportar Cuenta",
    viewNFT: "Ver NFT",
  },
  modals: {
    connectSentence: "Conectar una billetera",
    connectMetamask: "Conectar con Metamask",
    artistNotVerified:
      "No eres un artista verificado para poder sugerir cambios, verifícate y se parte de la comunidad!",
    artistNotVerified2:
      "No eres un artista verificado para poder crear NFTs en el marketplace, verifícate y se parte de la comunidad!",
    URLNotFound:
      "La página a la que intentas acceder no existe, es un misterio cómo has accedido a esta. Puedes pulsar el botón para dirigirte al Homepage de la página",
    confirmCreation: "Confirma tu creación",
    changedPrice: "NFT listado por {0} {1} correctamente",
    offerAccepted: "Oferta acceptada por {0} {1} correctamente",
    buyNowSuccess: "NFT comprado por {0} {1} correctamente",
    seeUpdatedItem: "Ver NFT actualizado",
    seeOwnedItem: "Ver NFT en posesión",
    buySuccess: "NFT comprado correctamente",
    notEnoughWftm: "No tienes suficientes {0} para comprar el NFT",
    offerMade: "Oferta por {0} {1} creada correctamente",
    bidPlaced: "Puja por {0} {1} creada correctamente",
    close: "Cerrar",
    sendReport: "Enviar Reporte",
    completedReport: "Tu reporte ha sido enviado y será revisado con detalle",
    reportDesc: "Mensaje del Reporte",
    reportInfo:
      "Explicanos porque estas reportando este contenido, se lo más detallado y transparente",
  },
  acceptOfferModal: {
    acceptOffer: "Aceptar oferta",
    doYouAccept: "Quieres aceptar la siguiente oferta?",
    isOffering: "Te ofrece",
  },
  actionModal: {
    error: "Ha ocurrido un error al realizar la acción",
  },
  buyItemModal: {
    name: "Nombre:",
    royalties: "Regalías:",
    notWFTM: "Insuficientes FTM para comprar!",
    fibboEarns: "Fibbo recoge un 2% de comisiones en cada venta de NFT",
  },
  buyNowModal: {
    buyItem: "Quieres comprar el NFT por",
  },
  cancelAuctionModal: {
    cancelAuction: "Cancelar Subasta",
    cancel: "Cancelar",
    canceledOk: "Subasta cancelada correctamente",
    reservedPrice: "Precio Reservado",
    highestBid: "Puja mas alta: ",
    doneBy: "Realizada Por:",
    doYouCancel: "Quieres cancelar la subasta?",
  },
  changePriceModal: {
    changePrice: "Cambiar precio del NFT",
    updatedItem: "Ver ítem acutalizado",
    price: "Precio",
  },
  confirmCreateCollection: {
    collectionCreated: "Colección creada correctamente",
    viewCollection: "Ver Colección Creada",
    customURL: "URL personalizada:",
  },
  confirmCreateModal: {
    collection: "Colección:",
    name: "Nombre:",
    description: "Descripción",
    royalties: "Regalías",
    aditionalContent: "Contenido adicional",
    createNFT: "Crear NFT",
    itemCreated: "NFT creado correctamente",
    viewItem: "Ver NFT Creado",
  },
  createAuctionModal: {
    auctionItem: "Subastar NFT",
    auction: "Poner en subasta",
    auctionCorrect: "NFT puesto en subasta correctamente",
    choosePrice: "Que precio quieres asegurar?",
    minBid: "Quieres que la puja mínima sea el precio reservado?",
    buyNowPrice: "Que precio de compra ahora?",
    errorPrice: "El precio de compra tiene que ser mínimo el doble de reserva",
    beginDate: "Fecha de Inicio",
    endDate: "Fecha de Fin",
  },
  deleteItemModal: {
    deleteNFT: "Eliminar NFT",
    delete: "Eliminar",
    viewCollection: "Ver colección",
    deletedOk: "El NFT se ha eliminado correctamente",
    ifYouAccept:
      "Una vez aceptes esta opción, el NFT será eliminado del marketplace y no se va a poder interactuar con el",
    confirmDelete: "¿Estas seguro de que quieres eliminarlo?",
    confirm: "Si, estoy seguro",
  },
  filtersSidebarModal: {
    close: "Cerrar menu",
    token: "Token",
    collections: "Colecciones",
  },
  freezeMetadataModal: {
    freezeMeta: "Congelar metadata del NFT",
    freeze: "Congelar",
    viewItem: "Ver el NFT",
    infoFreezed: "La información de tu ítem se ha congelado correctamente",
    ifYouAccept:
      "Una vez aceptes esta opción, la información del NFT no podrá ser editada y se almacenará de una forma descentralizada en el protocolo IPFS",
    correctInfo: "¿Estas seguro de que la información es correcta?",
    yes: "Si, estoy seguro",
  },
  modifyOfferModal: {
    modifyOffer: "Modificar oferta",
    update: "Actualizar",
    offerUpdated: "Oferta actualizada correctamente",
    viewOffer: "Ver tu oferta",
    price: "Que precio quieres ofertar?",
    expires: "Fecha de Expiración",
  },
  newBidModal: {
    makeBid: "Realizar puja",
    viewBid: "Ver tu puja",
    reservedPrice: "Precio Reservado",
    highestBid: "Puja mas alta:",
    doneBy: "Realizada Por:",
    bidPrice: "Que precio quieres pujar?",
    biggerBid: "La puja debe ser mayor a la actual",
    text1: "La diferencia con la puja actual debe ser 1 o mayor",
    text2: "La puja debe ser mayor o igual que el precio reservado",
  },
  putForSaleModal: {
    sellNft: "Poner NFT en venta",
    sellItem: "Poner NFT en venta",
    viewUpdated: "Ver ítem acutalizado",
  },
  redirectModal: {
    redirect: "Redirección a link externo",
    externalLink: "Vas a ser redireccionado a un enlace externo",
    fibboNotResponsable:
      "¡ FIBBO no se hace responsable de lo que pueda pasar !",
    dontShow: "No volver a mostrar díalogo",
    goToLink: "Ir al enlace",
  },
  removeOfferModal: {
    cancelYourOffer: "Cancelar tu oferta",
    cancelOffer: "Cancelar Oferta",
    canceledOk: "Oferta cancelada correctamente",
    updated: "Ver ítem acutalizado",
    cancel: "Quieres cancelar la oferta realizada?",
    you: "Tú",
    offer: "ofreces",
  },
  transferModal: {
    transfer: "Transferir NFT",
    send: "Enviar ítem",
    sendOk: "NFT enviado correctamente",
    itemUpdated: "Ver ítem acutalizado",
    wallet: "Introduce la dirección a la cual quieres enviarlo",
  },
  unlistItemModal: {
    quitItem: "Quitar ítem del mercado",
    deleteItem: "Eliminar ítem",
    deletedOk: "NFT eliminado del mercado correctamente",
    itemUpdated: "Ver ítem acutalizado",
    name: "Nombre:",
    royalties: "Regalías:",
  },
  updateAuctionModal: {
    updateAuction: "Actualizar Subasta",
    update: "Actualizar",
    auctionUpdated: "Subasta actualizada correctamente",
    reservedPrice: "Precio Reservado",
    newPrice: "El nuevo precio reservado debe ser diferente",
    beginDate: "Fecha de Inicio",
    endDate: "Fecha de Fin",
  },
  wrappedFTMModal: {
    station: "Esatación FTM / FTM",
    balance: "Balance",
    notFTM: "No tienes suficientes FTM para convertir",
    notWFTM: "No tienes suficientes FTM para retirar",
    changeWFTM: "Cambiar a FTM",
    sendFTM: "Retirar FTM",
    close: "Cerrar Estación",
    succesWrap: "Transformados correctamente {0} FTM a FTM",
    succesUnWrap: "Retirados correctamente {0} FTM",
  },
  editCollection: {
    title: "Editar Colección",
    notAllowed: "No puedes editar la colección, no eres su propietario!",
  },
  createItem: {
    colection: "Colección",
    name: "Name",
    description: "Descripción",
    descriptionDesc: "De 50 a 500 carácteres",
    descriptionError: "La descripción debe tener entre 50 y 500 carácteres",
    externalLink: "Enlace externo",
    externalLinkDesc:
      "Fibbo incluirá un enlace a este enlace en el detalle del NFT. Así los usuarios podrán tener mas información.",
    royalties: "Royalties",
    royaltiesDesc:
      "Recoge un porcentage cuando un usuario re-venda el ítem que originalmente creaste",
    royaltiesError:
      "Los royalties no puede ser mas de un 50% ni un valor negativo!",
    additionalContent: "Contenido Adicional",
    additionalContentPlaceholder:
      "Añade contenido (Clave de acceso, código, enlace a ficheros...)",
    additionalContentDesc:
      "Incluye contenido adicional que sólo el propietario podrá ver",

    notOwner:
      "No puedes crear NFTS, No eres el propietario de la colección. Crea una colección y añade NFTs en ella!",
    notOwnerEdit: "No puedes editar el NFT, No eres el propietario.",
    isFreezed: "El NFT no puede ser editado, tiene su metadata congelada",
    notOwnerEdit2:
      "No puedes editar el ítem, No eres el propietario de la colección.",
    freezeMetadata: "Congelar Metadata",
    selectImageError: "Selecciona una imágen",
    selectVideoError: "Selecciona un archivo de video",
    selectAudioError: "Selecciona un archivo de audio",
    sizeError: "El contenido pesa más de  50MB, selecciona otro",

    image: "Imágen",
    video: "Vídeo",
    audio: "Audio",
  },
  events: {
    minted: "NFT minteado",
    listed: "NFT Listado",
    transfer: "Transfer",
    changedPrice: "Precio Actualizado",
    unlisted: "Quitado en venta",
    offerCreated: "Oferta creada",
    offerModified: "Oferta Modificada",
    offerCanceled: "Oferta cancelada",
    offerAccepted: "Oferta acceptada",
    auctionCreated: "Subasta creada",
    bidded: "Puja realizada",
    auctionUpdate: "Subasta Actualizada",
    auctionCanceled: "Subasta cancelada",
    auctionEnded: "Subasta Finalizada",
  },
};

export { engLiterals, espLiterals };
